def mostrar_menu():
    print("Menu:")
    print("1. Ingresar proyecto")
    print("2. Modificar proyecto")
    print("3. Cancelar proyecto")
    print("4. Comprobar proyectos")
    print("5. Mostrar todos")
    print("6. Calcular presupuesto promedio")
    print("7. Buscar proyecto por nombre")
    print("8. Ordenar proyectos")
    print("9. Retomar proyecto")
    print("10. Generar reporte de presupuesto superior")
    print("11. Generar informe de búsqueda por nombre")
    print("12. Salir")

def mostrar_submenu_modificar_proyecto():
    print("-----Submenu para modificar proyecto-----")
    print("1.modificar nombre del proyecto")
    print("2.modificar descripción del proyecto")
    print("3.modificar presupuesto del proyecto")
    print("4.modificar fecha de inicio del proyecto manualmente")
    print("5.modificar fecha de fin de proyecto")
    print("6.modificar estado del proyecto")
    print("7.Salir")

def mostrar_submenu_cambiar_estado():
    print("--submenu_cambiar_estado--")
    print("1.Establecer estado Activo")
    print("2.Establecer estado Cancelado")
    print("3.Establecer estado finalizado")
    print("4.Salir")
